language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

notifications:
  email: false
  slack:
    secure: Sz+7ETAeGvtnuq8dclS8UQeTaQx+JL8apWpWSw1b0WvctH8pmJmvk+YNQ5fhi+4and35a1c/j0FfP/m15fkRR2fn+y5KK/NTnbJu/xVdSBonYFeHuQhsmUACZwPzLSZTxlAt+VT/ncG77jSR4HglzqDltlKnVvDinsS288Oovo4=

before_install:
  # Set the GitHub OAuth token to make use of the 6000 per hour rate limit
  # This is read only token for only public repos
  - "mkdir -p ~/.composer"
  - mv .travis.composer.config.json ~/.composer/config.json
  - composer selfupdate

install:
  - composer install

before_script:
  - mkdir -p build/logs
  - mysql -e 'create database `harp-orm/query`;'
  - mysql --default-character-set=utf8 harp-orm/query < tests/mysql.sql

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - test -e build/logs/clover.xml && wget https://scrutinizer-ci.com/ocular.phar
  - test -e build/logs/clover.xml && php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
